apiVersion: v1
kind: Service
metadata:
  annotations:
    more.info: https://github.com/for1337
  creationTimestamp: null
  labels:
    io.kompose.service: espocrm-websocket
  name: espocrm-websocket
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: espocrm-websocket
status:
  loadBalancer: {}
