apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    more.info: https://github.com/for1337
  creationTimestamp: null
  labels:
    io.kompose.service: espocrm-daemon
  name: espocrm-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: espocrm-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        more.info: https://github.com/for1337
      creationTimestamp: null
      labels:
        io.kompose.service: espocrm-daemon
    spec:
      containers:
        - command:
            - docker-daemon.sh
          image: espocrm/espocrm
          name: espocrm-daemon
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: espocrm
      restartPolicy: Always
      volumes:
        - name: espocrm
          persistentVolumeClaim:
            claimName: espocrm
status: {}
